name: Mon Premier Workflow de Démo
on:
  push:
    branches: [main]
jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, CI/CD !"
      - run: ls -la
      - name: Vérifier la version de Python
        run: python --version
        